services:
  - type: web
    name: ecuaciones
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn math_project.wsgi:application"
    envVars:
      - key: python
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true
